# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPUi4-f3016aifMHmG62Mlvl50uaSCJe
"""

import streamlit as st
from datetime import datetime, date
import pandas as pd

# --------------------------
#    SESSION STATE SETUP
# --------------------------
def init_session_state():
    if "goals" not in st.session_state:
        st.session_state["goals"] = []

# --------------------------
#        ADD GOAL
# --------------------------
def add_goal(name, target_amount, target_date):
    st.session_state["goals"].append(
        {
            "name": name,
            "target_amount": float(target_amount),
            "target_date": target_date,
            "created_at": datetime.today().date(),
        }
    )

# --------------------------
#  BUILD SAVINGS TABLE
# --------------------------
def build_goals_df():
    if not st.session_state["goals"]:
        return pd.DataFrame()

    rows = []
    today = datetime.today().date()

    for g in st.session_state["goals"]:
        due = g["target_date"]

        if isinstance(due, pd.Timestamp):
            due = due.date()

        amount = g["target_amount"]
        days_left = (due - today).days

        if days_left <= 0:
            daily = weekly = amount
            status = "⚠️ Due or passed"
        else:
            daily = amount / days_left
            weekly = daily * 7
            status = "✔️ On track"

        rows.append(
            {
                "Goal": g["name"],
                "Target amount (€)": round(amount, 2),
                "Target date": due,
                "Days left": days_left,
                "Daily saving (€)": round(daily, 2),
                "Weekly saving (€)": round(weekly, 2),
                "Status": status,
            }
        )

    return pd.DataFrame(rows)

# --------------------------
#           MAIN APP
# --------------------------
def main():
    st.set_page_config(
        page_title="Save Now, Pay Later",
        page_icon="💰",
        layout="wide"
    )

    init_session_state()

    st.title("💰 Save Now, Pay Later")
    st.caption("A simple predictive savings app that helps you save ahead of your goals.")

    menu = st.sidebar.radio(
        "Navigation",
        ["🏁 Goals & Saving Plans", "📊 Overview / Simulation", "ℹ️ Help"]
    )

    # -----------------------------------
    #  PAGE 1 — GOALS & SAVINGS PLANS
    # -----------------------------------
    if menu == "🏁 Goals & Saving Plans":
        st.header("🏁 Define your saving goals")

        with st.form("add_goal_form"):
            name = st.text_input("Goal name", placeholder="Trip to Barcelona, New iPhone, etc.")

            col1, col2 = st.columns(2)

            with col1:
                target_amount = st.number_input(
                    "Target amount (€)", min_value=1.0, step=10.0, value=100.0
                )

            with col2:
                target_date = st.date_input("Target date", value=date.today())

            submitted = st.form_submit_button("Add goal")

            if submitted:
                if not name:
                    st.error("Please enter a goal name.")
                else:
                    add_goal(name, target_amount, target_date)
                    st.success(f"Goal '{name}' added!")

        df_goals = build_goals_df()

        if df_goals.empty:
            st.info("Add a goal above to get started.")
        else:
            st.subheader("Your goals")
            st.dataframe(df_goals, use_container_width=True)

            total_target = df_goals["Target amount (€)"].sum()
            st.metric("Total amount to save (€)", f"{total_target:,.2f}")

    # -----------------------------------
    #       PAGE 2 — OVERVIEW
    # -----------------------------------
    elif menu == "📊 Overview / Simulation":
        st.header("📊 Goals Overview")

        df_goals = build_goals_df()

        if df_goals.empty:
            st.info("No goals yet. Add one in the first page.")
        else:
            st.subheader("Timeline")
            st.dataframe(
                df_goals[["Goal", "Target amount (€)", "Target date", "Days left"]],
                use_container_width=True
            )

            monthly_needed = df_goals["Daily saving (€)"].sum() * 30
            st.metric("Estimated monthly savings needed", f"{monthly_needed:,.2f} €")

            st.write("This approximation assumes 30 days/month.")

    # -----------------------------------
    #         PAGE 3 — HELP
    # -----------------------------------
    else:
        st.header("ℹ️ Help / About")

        st.markdown("""
### Welcome to Save Now, Pay Later!
This app helps you plan savings based on your future goals.

#### How it works:
1. Add your financial goals (target amount + deadline).
2. The app calculates:
   - Days left
   - Daily savings needed
   - Weekly savings needed
   - Total monthly savings needed
3. Use the overview page to see how much you must save each month.

---

Prototype version 1.
Created for your FinTech project.
        """)

# --------------------------
#        RUN APP
# --------------------------
if __name__ == "__main__":
    main()